# Changes here will be overwritten by Copier
_commit: 3249a90
_src_path: gh:alleninstitute/copier-pdm-npc
add_requirements_txt: true
author_email: ben.hardcastle@alleninstitue.org, arjun.sridhar@alleninstitute.org
author_fullname: Ben Hardcastle, Arjun Sridhar
author_username: bjhardcastle, arjunsridhar12345
build_doc: true
copyright_date: '2024'
copyright_holder: Allen Institute for Neural Dynamics
copyright_holder_email: ''
copyright_license: MIT
package_version: 0.1.0
project_description: Type to store metadata for dynamic routing experiments at Allen
    Institute
project_name: ndx-dynamic-routing-metadata
python_package_distribution_name: ndx-dynamic-routing-metadata
python_package_import_name: ndx_dynamic_routing_metadata
python_package_requires_python: '>=3.8'
repository_name: ndx-dynamic-routing-metadata
repository_namespace: AllenInstitute

